### PR TITLE
fix for jQuery 3.0

### PR DESCRIPTION
**Pull request by tomek-f**
All demos work with jQuery 3.0 after fix

### CODE REVIEW

**Comment by mdeboer** [comment]
Can we get this merged please? 👍

**Comment by CracyCrazz** [comment]
I've committed those changes in my own branch. It is now available in the latest release.

**Comment by pencilpix** [comment]
installation via npm is not working for version above 2.1.4 !

**Comment by daviddeutsch** [comment]
@pencilpix fixed now!

**Pull request closed without merging**
