### PR TITLE
pulling left on end of carousel less than 30 causes a jump several it…

### PR DESCRIPTION
**Pull request by ghost**
drags under the 'threshold for click event' cause the carousel to jump to the last element. Removed the click threshold to stop the jumping.

### CODE REVIEW

**Comment by tsmith-dep** [comment]
I have the same issue occuring, but it doesn't seem to be caused by drags under the threshold. It appears to be almost random. I attempted to use this change, and it definitely didn't fix the issue for me Unfortunately.

**Comment by ghost** [comment]
I made an additional modifications under my fork to stop it from jumping.   Not sure if it helps you out.
https://github.com/svandevoorde/OwlCarousel2/tree/master

		**if (this.closest(stage.x, delta.x !== 0 ? direction : this._drag.direction) !== -1) {**
			if (delta.x !== 0 && this.is('dragging') || !this.is('valid')) {
				this.speed(this.settings.dragEndSpeed || this.settings.smartSpeed);
				this.current(this.closest(stage.x, delta.x !== 0 ? direction : this._drag.direction));
				this.invalidate('position');
				this.update();

				this._drag.direction = direction;
				this._drag.target.one('click.owl.core', function() { return false; });
		}
		**}**

**Comment by tsmith-dep** [comment]
Thanks I ended up finding my solution over here thanks to hexplor
https://github.com/OwlCarousel2/OwlCarousel2/issues/1771

**Comment by pascalporedda** [comment]
This has been fixed with another PR.

**Pull request closed without merging**
