### PR TITLE
Fixing over-sensitive rightward swipe on touch devices

### PR DESCRIPTION
**Pull request by e2tha-e**
choosing correct index to test whether pull distance exceeds threshold

### CODE REVIEW

**Comment by e2tha-e** [comment]
Ref issue #947

**Comment by daviddeutsch** [comment]
Yeah, looks good! Thanks so much for the contribution!

**Comment by e2tha-e** [comment]
@daviddeutsch Wow! Thanks for the merge! This carousel worked beautifully but for a few issues like this one. I had been thinking it was abandoned for some time. Thanks for keeping it alive!

**Comment by daviddeutsch** [comment]
Doing my best to get up to speed and keep track of all the wonderful submissions. Pleasure is all mine!

**Pull request merged**
