### PR TITLE
added lazyload support for srcset (responsive images)

### PR DESCRIPTION
**Pull request by wstoettinger**

### CODE REVIEW

**Comment by leecollings** [comment]
I notice this was submitted way over a year ago, did this ever make it into a release?

**Comment by gsc89** [comment]
Same question. ^

**Comment by crazypsycho** [comment]
I would be really nice if this came to next release. But i found this alternative:
https://github.com/LudoBermejo/owl.lazy.srcset/blob/master/owl.lazy.srcset.js
But i dont know if this works, didnt testet yet.

**Comment by danb18** [comment]
Did this ever make it into a release? I am also wanting to use this feature.

**Comment by irinayeee** [comment]
It would be nice to have data-sizes attribute as well.

**Comment by thuctonhuyen** [comment]
I think it doesnt work on IE9?

**Comment by pascalporedda** [comment]
I have to close this PR, as there has been a newer one that implemented these changes.

**Pull request closed without merging**
