### PR TITLE
Fixed issue on touchscreen devices when you can't vertically scroll.

### PR DESCRIPTION
**Pull request by exil0867**
Fix to issue #2143

### CODE REVIEW

**Comment by pascalporedda** [comment]
Hey @ExillustX 

You would have to make these changes to the according src files not the minified version.

**Comment by noval121198** [comment]
thx u , problem solved

**Comment by M-Marcel** [comment]
Thank you...

**Comment by foodpara51** [comment]
Thanks It worked for me as well

**Comment by nestle49** [comment]
DONT WORK

**Pull request closed without merging**
