### PR TITLE
[feature #981] - add css easing option

### PR DESCRIPTION
**Pull request by CHEWX**
Created a CSS easing option for modern browsers, set the default to linear.

### CODE REVIEW

**Comment by OwlCarousel2** [comment]
@CHEWX I am no longer able to maintain this repo. If you are interested in taking over ownership, please let me know.

**Comment by jonathantneal** [comment]
Hey @OwlCarousel2, I emailed you to offer my help. Just replying here in case it gets to you first.

**Comment by CHEWX** [comment]
@daviddeutsch Hi, do you think this will be merged in ?

**Comment by pascalporedda** [comment]
We actually provide this option now.

**Pull request closed without merging**
