### PR TITLE
adding onResize to Owl.prototype.refresh

### PR DESCRIPTION
**Pull request by e2tha-e**

### CODE REVIEW

**Comment by e2tha-e** [comment]
Ref issue #948

**Comment by yongtw123** [comment]
This helps solve https://github.com/smashingboxes/OwlCarousel2/issues/792 by allowing `refresh` to trigger recalculation of `owl-item` width.

**Comment by daviddeutsch** [comment]
Hey @e2tha-e - thanks for the contribution! One problem, though: Isn't this creating a circular call? `onResize` calls `refresh`, which in turn calls `onResize`...

**Comment by e2tha-e** [comment]
@daviddeutsch I updated the pr. Please re-review. Thanks!

**Comment by daviddeutsch** [comment]
Almost there! The last thing I have a problem with now is that you redeclare the new variable you introduced. Instead, it's a better idea to just check for it being undefined and setting it to a default if it isn't set.

**Comment by e2tha-e** [comment]
@daviddeutsch Ok. So I'm setting it to a default. I think that's covered now. Please re-review.

**Comment by e2tha-e** [comment]
Not sure if this was not re-reviewed because of the broken Travis build, but the build is fixed now. Please re-review.

**Pull request merged**
