### PR TITLE
Small fix to prevent the glitch that stops autoplay when you switch to another tab

### PR DESCRIPTION
**Pull request by PerfectByte**
By removing this._core.is('busy') the carousel no longer stops autoplay when you switch to another tab and come back, instead pausing the carousel and resuming when switching back as intended.

### CODE REVIEW

**Comment by PerfectByte** [comment]
travis-ci failing seems to be a result of phantomjs not my actual changes

**Comment by pascalporedda** [comment]
Hey @PerfectByte 

I would like to merge that changes, but you would have to resolve the merge conflicts first.

**Comment by PerfectByte** [comment]
Hi @pascalporedda 

I fixed the merge conflicts. Feel free the merge the changes :)

**Comment by pascalporedda** [comment]
Hey @PerfectByte 

you've made those changes directly into the distributes files, I've taken your changes and put them into the correct place. Tested it and everything is working correctly. Thank you for this fix.

**Pull request closed without merging**
