### PR TITLE
youtube url parameter support

### PR DESCRIPTION
**Pull request by eparisio**
basic support for parameters in the youtube url passed to the plugin:
* if parameters are passed (after ?) the plugin will use them plus the autoplay, otherwise only autoplay will be set

### CODE REVIEW

**Comment by greg5green** [comment]
This looks like a pretty cool idea and we'll be looking into merging it in when we can!

cc #846

**Comment by StApostol** [comment]
@eparisio When check this fix?

**Comment by daviddeutsch** [comment]
I'll be looking into merging this, the main issue, however is that your PR holds a lot of commits unrelated (or am I missing something?) to the yt parameter feature. @eparisio Would you mind cleaning those up so we can move forward?

**Comment by eparisio** [comment]
i have made a new pull request with an updated and clean branch:
#1310

**Comment by daviddeutsch** [comment]
Thanks! I'll close this, then.

**Pull request closed without merging**
